# Platform and architecture detection for libpqc-dyber

# Detect OS
if(WIN32)
    set(PQC_PLATFORM "windows")
    set(PQC_OS_WINDOWS ON)
elseif(APPLE)
    set(PQC_PLATFORM "macos")
    set(PQC_OS_MACOS ON)
elseif(CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
    set(PQC_PLATFORM "freebsd")
    set(PQC_OS_FREEBSD ON)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(PQC_PLATFORM "linux")
    set(PQC_OS_LINUX ON)
    # Detect distro
    if(EXISTS "/etc/redhat-release")
        file(READ "/etc/redhat-release" _redhat_release)
        if(_redhat_release MATCHES "Fedora")
            set(PQC_DISTRO "fedora")
        elseif(_redhat_release MATCHES "Red Hat")
            set(PQC_DISTRO "rhel")
        endif()
    endif()
else()
    set(PQC_PLATFORM "unix")
    set(PQC_OS_UNIX ON)
endif()

# Detect architecture
if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64|amd64)$")
    set(PQC_ARCH "x86_64")
    set(PQC_ARCH_X86_64 ON)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64|ARM64)$")
    set(PQC_ARCH "aarch64")
    set(PQC_ARCH_AARCH64 ON)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(i[3-6]86|x86)$")
    set(PQC_ARCH "x86")
    set(PQC_ARCH_X86 ON)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm|ARM)")
    set(PQC_ARCH "arm")
    set(PQC_ARCH_ARM ON)
else()
    set(PQC_ARCH "generic")
    set(PQC_ARCH_GENERIC ON)
endif()

message(STATUS "Detected platform: ${PQC_PLATFORM} (${PQC_ARCH})")
